services:
  web:
    image: h5ai:latest
    container_name: h5ai-web
    ports:
      - "80:80"
    volumes:
      - ./data:/h5ai
    environment:
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      fgofile:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  fgofile:
    image: fgofile:latest
    container_name: h5ai-fgofile
    environment:
      - FGO_PORT=2121
      - FGO_ROOT=/h5ai
      # - FGO_USER=user
      # - FGO_PASS=pass
    command: ["/bin/sh", "-lc", "fgofile --server --port ${FGO_PORT:-2121} --root ${FGO_ROOT:-/h5ai} $( [ -n \"$FGO_USER\" -a -n \"$FGO_PASS\" ] && printf -- ' --suser %s --spass %s' \"$FGO_USER\" \"$FGO_PASS\" )"]
    volumes:
      - ./data:/h5ai
    ports:
      - "2121:${FGO_PORT:-2121}"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost ${FGO_PORT:-2121}"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
