services:
  web:
    image: h5ai:latest
    container_name: h5ai-web
    ports:
      - "80:80"
    volumes:
      - ./data:/h5ai
    environment:
      TZ: Asia/Ho_Chi_Minh
    depends_on:
      - fgofile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  fgofile:
    build:
      context: .
      dockerfile: Dockerfile.fgofile
    image: fgofile:latest
    container_name: h5ai-fgofile
    environment:
      FGO_PORT: 2121
      FGO_ROOT: /h5ai
      FGO_USER: user
      FGO_PASS: pass
    volumes:
      - ./data:/h5ai
    ports:
      - "2121:2121"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 2121"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
