FROM nginx:1.27-alpine3.19
LABEL org.opencontainers.image.authors="polarisdp@gmail.com"

ENV TZ='Asia/Ho_Chi_Minh' \
    PUID=1000 \
    PGID=1000

RUN apk update && apk add --no-cache \
    bash bash-completion supervisor tzdata shadow curl \
    php82 php82-fpm php82-session php82-json php82-xml php82-mbstring php82-exif \
    php82-intl php82-gd php82-pecl-imagick php82-zip php82-opcache \
    ffmpeg imagemagick zip && \
    rm -rf /var/cache/apk/* && \
    mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak

COPY ./h5ai/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./h5ai/nginx.conf /etc/nginx/nginx.conf
COPY ./h5ai/php_set_timezone.ini /etc/php82/conf.d/00_timezone.ini
COPY ./h5ai/php_set_jit.ini /etc/php82/conf.d/00_jit.ini
COPY ./h5ai/php_set_memory_limit.ini /etc/php82/conf.d/00_memlimit.ini
COPY ./h5ai/php_h5ai_optimizations.ini /etc/php82/conf.d/01_h5ai_optimizations.ini
COPY ./h5ai/h5ai.conf /etc/nginx/conf.d/h5ai.conf

RUN mkdir -p /usr/share/h5ai/_h5ai
COPY ./h5ai/_h5ai /usr/share/h5ai/_h5ai

COPY --chmod=755 ./h5ai/entrypoint.sh /entrypoint.sh

RUN mkdir -p /config /h5ai && \
    chown -R nginx:nginx /config /h5ai

EXPOSE 80
VOLUME ["/config", "/h5ai"]

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -f http://localhost/ || exit 1

ENTRYPOINT ["/entrypoint.sh"]
